# Configuration file for multiple Tello drones
drones:
  - name: tello7
    node_name: tello_driver
    drone_ip: '192.168.0.107'
    command_port: 38065
    drone_port: 9007
    data_port: 8007
    video_port: 11107
    uwb_tag_id: 1

  - name: tello4
    node_name: tello_driver
    drone_ip: '192.168.0.104sss'
    command_port: 38064
    drone_port: 9004
    data_port: 8004
    video_port: 11104
    uwb_tag_id: 2

  - name: tello17
    node_name: tello_driver
    drone_ip: '192.168.0.117'
    command_port: 38066
    drone_port: 9017
    data_port: 8017
    video_port: 11117
    uwb_tag_id: 3

  - name: tello1
    node_name: tello_driver
    drone_ip: '192.168.0.101'
    command_port: 38067
    drone_port: 9001
    data_port: 8001
    video_port: 11101
    uwb_tag_id: 4
